package com.pregnant.health.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CATALOG".
 */
public class Catalog implements java.io.Serializable {

    private Long id;
    private String name;
    private String code;
    private String caption;
    private String defaultValue;
    private String tableName;
    private String fieldName;
    private String remark;
    private String addTime;
    private String updateTime;
    private String children;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Catalog() {
    }

    public Catalog(Long id) {
        this.id = id;
    }

    public Catalog(Long id, String name, String code, String caption, String defaultValue, String tableName, String fieldName, String remark, String addTime, String updateTime, String children) {
        this.id = id;
        this.name = name;
        this.code = code;
        this.caption = caption;
        this.defaultValue = defaultValue;
        this.tableName = tableName;
        this.fieldName = fieldName;
        this.remark = remark;
        this.addTime = addTime;
        this.updateTime = updateTime;
        this.children = children;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCaption() {
        return caption;
    }

    public void setCaption(String caption) {
        this.caption = caption;
    }

    public String getDefaultValue() {
        return defaultValue;
    }

    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getFieldName() {
        return fieldName;
    }

    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getAddTime() {
        return addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public String getChildren() {
        return children;
    }

    public void setChildren(String children) {
        this.children = children;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
